version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - revive
  exclusions:
    paths:
      - frontend/node_modules
  settings:
    revive:
      rules:
        - name: exported
        - name: package-comments
        - name: comment-spacings
