// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListKeys() {
  return window['go']['main']['App']['ListKeys']();
}

export function SaveKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveKey'](arg1, arg2, arg3);
}
