// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyKey(arg1) {
  return window['go']['main']['App']['CopyKey'](arg1);
}

export function DeleteKey(arg1) {
  return window['go']['main']['App']['DeleteKey'](arg1);
}

export function ListKeys() {
  return window['go']['main']['App']['ListKeys']();
}

export function SaveKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveKey'](arg1, arg2, arg3);
}

export function UpdateKey(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateKey'](arg1, arg2, arg3, arg4);
}
